[2024-08-27T14:34:41.967+0000] {processor.py:186} INFO - Started process (PID=5540) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:34:41.968+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:34:41.970+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:34:41.969+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:34:41.973+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:34:41.973+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:34:41.974+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:34:41.974+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:34:41.974+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:34:41.986+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-27T14:35:47.630+0000] {processor.py:186} INFO - Started process (PID=5611) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:35:47.631+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:35:47.633+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:35:47.633+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:35:47.637+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:35:47.636+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:35:47.637+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:35:47.637+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:35:47.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:35:47.649+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-27T14:36:40.639+0000] {processor.py:186} INFO - Started process (PID=5683) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:36:40.640+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:36:40.643+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:36:40.642+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:36:40.646+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:36:40.645+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:36:40.646+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:36:40.646+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:36:40.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:36:40.659+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-27T14:37:35.872+0000] {processor.py:186} INFO - Started process (PID=5759) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:37:35.874+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:37:35.876+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:37:35.876+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:37:35.880+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:37:35.879+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:37:35.880+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:37:35.880+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:37:35.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:37:35.892+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-27T14:38:26.587+0000] {processor.py:186} INFO - Started process (PID=5824) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:38:26.589+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:38:26.591+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:38:26.590+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:38:26.594+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:38:26.594+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:38:26.595+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:38:26.595+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:38:26.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:38:26.607+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-27T14:39:34.960+0000] {processor.py:186} INFO - Started process (PID=5906) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:39:34.962+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:39:34.965+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:39:34.964+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:39:34.968+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:39:34.967+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:39:34.969+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:39:34.968+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:39:34.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:39:34.981+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-27T14:40:28.013+0000] {processor.py:186} INFO - Started process (PID=5975) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:40:28.015+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:40:28.017+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:40:28.017+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:40:28.021+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:40:28.020+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:40:28.021+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:40:28.021+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:40:28.021+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:40:28.033+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-27T14:41:18.323+0000] {processor.py:186} INFO - Started process (PID=6027) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:41:18.325+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:41:18.327+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:41:18.327+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:41:18.330+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:41:18.330+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:41:18.331+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:41:18.331+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:41:18.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:41:18.343+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-27T14:42:06.963+0000] {processor.py:186} INFO - Started process (PID=6077) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:42:06.965+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:42:06.967+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:42:06.967+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:42:06.971+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:42:06.970+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:42:06.971+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:42:06.971+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:42:06.971+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:42:06.983+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-27T14:42:59.189+0000] {processor.py:186} INFO - Started process (PID=6129) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:42:59.191+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:42:59.193+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:42:59.193+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:42:59.197+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:42:59.196+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:42:59.197+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:42:59.197+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:42:59.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:42:59.212+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-08-27T14:43:48.458+0000] {processor.py:186} INFO - Started process (PID=6181) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:43:48.461+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:43:48.463+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:43:48.462+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:43:48.467+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:43:48.466+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:43:48.467+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:43:48.467+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:43:48.467+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:43:48.480+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-27T14:44:39.481+0000] {processor.py:186} INFO - Started process (PID=6234) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:44:39.482+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:44:39.485+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:44:39.484+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:44:39.488+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:44:39.488+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:44:39.489+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:44:39.488+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:44:39.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:44:39.501+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-27T14:45:30.095+0000] {processor.py:186} INFO - Started process (PID=6288) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:45:30.097+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:45:30.099+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:45:30.099+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:45:30.103+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:45:30.102+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:45:30.103+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:45:30.103+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:45:30.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:45:30.116+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-27T14:46:20.351+0000] {processor.py:186} INFO - Started process (PID=6343) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:46:20.353+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:46:20.355+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:46:20.355+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:46:20.359+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:46:20.358+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:46:20.359+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:46:20.359+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:46:20.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:46:20.371+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-27T14:47:30.419+0000] {processor.py:186} INFO - Started process (PID=6415) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:47:30.421+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:47:30.424+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:47:30.423+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:47:30.427+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:47:30.427+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:47:30.428+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:47:30.428+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:47:30.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:47:30.439+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-27T14:48:22.781+0000] {processor.py:186} INFO - Started process (PID=6473) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:48:22.783+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:48:22.785+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:48:22.785+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:48:22.789+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:48:22.788+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:48:22.789+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:48:22.789+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:48:22.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:48:22.801+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-27T14:49:13.185+0000] {processor.py:186} INFO - Started process (PID=6527) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:49:13.186+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T14:49:13.189+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:49:13.189+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:49:13.193+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:49:13.192+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T14:49:13.193+0000] {logging_mixin.py:190} INFO - [2024-08-27T14:49:13.193+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T14:49:13.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T14:49:13.206+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-27T16:10:12.740+0000] {processor.py:186} INFO - Started process (PID=7620) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:10:12.742+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T16:10:12.744+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:10:12.743+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:10:12.748+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:10:12.747+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T16:10:12.748+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:10:12.748+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T16:10:12.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:10:12.761+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-27T16:11:08.491+0000] {processor.py:186} INFO - Started process (PID=7716) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:11:08.492+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T16:11:08.494+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:11:08.494+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:11:08.498+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:11:08.497+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T16:11:08.498+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:11:08.498+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T16:11:08.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:11:08.511+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-27T16:12:04.006+0000] {processor.py:186} INFO - Started process (PID=7847) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:12:04.008+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T16:12:04.010+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:12:04.010+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:12:04.014+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:12:04.013+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T16:12:04.014+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:12:04.014+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T16:12:04.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:12:04.027+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-27T16:12:54.368+0000] {processor.py:186} INFO - Started process (PID=7937) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:12:54.370+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T16:12:54.372+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:12:54.371+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:12:54.375+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:12:54.375+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T16:12:54.376+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:12:54.376+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T16:12:54.376+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:12:54.390+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-27T16:13:46.968+0000] {processor.py:186} INFO - Started process (PID=8029) to work on /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:13:46.970+0000] {processor.py:914} INFO - Processing file /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-27T16:13:46.972+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:13:46.972+0000] {dagbag.py:587} INFO - Filling up the DagBag from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:13:46.976+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:13:46.975+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-27T16:13:46.976+0000] {logging_mixin.py:190} INFO - [2024-08-27T16:13:46.976+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-27T16:13:46.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-27T16:13:46.989+0000] {processor.py:208} INFO - Processing /home/ubuntu/myenv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
